spring.application.name=risk-central-mock-service
server.port=8081

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true

logging.level.com.coopcredit.riskmock=DEBUG
logging.level.org.springframework.web=INFO

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n
